services:
  redis:
    image: redis:7.0-alpine
    container_name: alpine-redis
    ports:
      - 6379:6379

  api:
    image: ankitpwr/fintel-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fintel-api
    command: ["bun", "run", "start"]
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  worker:
    image: ankitpwr/fintel-agent
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fintel-agent
    command: ["bun", "run", "worker"]
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    image: ankitpwr/fintel-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_CLIENT_ID=558738573808-3l6ciqpu6clqp69miea1hkhhs1gshft9.apps.googleusercontent.com
        - VITE_BASE_URL=https://orbitbackend.sketch.qzz.io/api/v1
    container_name: fintel-frontend
    ports:
      - 5173:80
    env_file:
      - ./client/.env
